<a href="https://colab.research.google.com/github/bifinbabu/nlp-jupyter-notebook/blob/main/text_representation_using_bag_of_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np

In [56]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [57]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [58]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [59]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [60]:
# from re import X
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [61]:
X_train.shape

(4457,)

In [62]:
X_test.shape

(1115,)

In [63]:
type(X_train)

pandas.core.series.Series

In [64]:
X_train[:4]

5513    Yes. Please leave at  &lt;#&gt; . So that at  ...
1233                          1's finish meeting call me.
5432                               Thanx a lot 4 ur help!
5466    http//tms. widelive.com/index. wml?id=820554ad...
Name: Message, dtype: object

In [65]:
type(y_train)

pandas.core.series.Series

In [66]:
y_train[:4]

5513    0
1233    0
5432    0
5466    1
Name: spam, dtype: int64

In [68]:
X_train[:4][1233]

"1's finish meeting call me."

In [69]:
y_train[:4]

5513    0
1233    0
5432    0
5466    1
Name: spam, dtype: int64

In [70]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)

X_train_cv

<4457x7750 sparse matrix of type '<class 'numpy.int64'>'
	with 59181 stored elements in Compressed Sparse Row format>

In [71]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [72]:
X_train_cv.shape

(4457, 7750)

In [73]:
v.get_feature_names_out()[1000:1050]

array(['anyhow', 'anymore', 'anyone', 'anyones', 'anyplaces', 'anythiing',
       'anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'apart', 'apartment', 'apes', 'apeshit',
       'aphex', 'apnt', 'apo', 'apologise', 'apologize', 'app',
       'apparently', 'appeal', 'appear', 'applebees', 'apples',
       'application', 'apply', 'applyed', 'appointment', 'appointments',
       'appreciate', 'appreciated', 'approaches', 'approaching',
       'appropriate', 'approved', 'apps', 'appt', 'appy', 'april',
       'aproach', 'apt', 'aquarius', 'ar', 'arab', 'arabian', 'arcade'],
      dtype=object)

In [74]:
v.vocabulary_

{'yes': 7694,
 'please': 5267,
 'leave': 4073,
 'at': 1122,
 'lt': 4268,
 'gt': 3279,
 'so': 6304,
 'that': 6815,
 'we': 7424,
 'can': 1642,
 'finish': 2871,
 'meeting': 4437,
 'call': 1618,
 'me': 4419,
 'thanx': 6813,
 'lot': 4232,
 'ur': 7200,
 'help': 3418,
 'http': 3551,
 'tms': 6935,
 'widelive': 7517,
 'com': 1912,
 'index': 3677,
 'wml': 7576,
 'id': 3601,
 '820554ad0a1705572711': 657,
 'first': 2885,
 'true': 7053,
 'ringtone': 5817,
 'each': 2521,
 'moment': 4578,
 'in': 3654,
 'day': 2203,
 'has': 3360,
 'its': 3778,
 'own': 5056,
 'value': 7249,
 'morning': 4600,
 'brings': 1523,
 'hope': 3507,
 'afternoon': 858,
 'faith': 2772,
 'evening': 2678,
 'luv': 4284,
 'night': 4792,
 'rest': 5774,
 'wish': 7550,
 'find': 2866,
 'them': 6827,
 'all': 917,
 'today': 6946,
 'good': 3202,
 'not': 4842,
 'watching': 7409,
 'movie': 4619,
 'already': 928,
 'xy': 7666,
 'wants': 7389,
 'shop': 6128,
 'shopping': 6130,
 'her': 3428,
 'now': 4857,
 'rct': 5609,
 'thnq': 6862,
 'adrian': 83

In [75]:
v.get_feature_names_out()[1102]

'askin'

In [76]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [77]:
np.where(X_train_np[0] != 0)

(array([1122, 1642, 3279, 4073, 4268, 5267, 6304, 6815, 7424, 7694]),)

In [79]:
X_train[:4][1233]

"1's finish meeting call me."

In [80]:
X_train_np[0][1063]

0

In [81]:
X_train_np[0][1642]

1

In [82]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv, y_train)

MultinomialNB()

In [83]:
X_test_cv = v.transform(X_test)

In [84]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       962
           1       0.97      0.88      0.92       153

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [85]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [86]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [87]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [88]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       962
           1       0.97      0.88      0.92       153

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115

